### ISSUE TITLE
Campaign Tags

### ISSUE THREAD

**Issue by nananananate** [grasshopperfund/grasshopperfund#14]

**Comment by PeterOR2D2** [comment]
Campaigns without existing tags: 
![campaign_without_existing_tags](https://user-images.githubusercontent.com/32473119/99136560-7589de80-25da-11eb-9306-aca8e83ba1d0.gif)

Campaigns with existing tags: 
![campaign_with_existing_tags](https://user-images.githubusercontent.com/32473119/99136590-b4b82f80-25da-11eb-9731-d912f759b067.gif)

**Comment by PeterOR2D2** [comment]
If the migrations for campaigns and / or tags got deleted or want to delete those two migrations, use this command: 
![image](https://user-images.githubusercontent.com/32473119/99136667-314b0e00-25db-11eb-9fea-68a26b8f9467.png)

python manage.py makemigrations campaigns tags

Thanks.

**Comment by nananananate** [comment]
Awesome @PeterOR2D2 ! Also, can you let me know of any database changes that are inconsistent with the current ER Diagram? I'd like to update it if you've made any changes, as it will aid in the onboarding process. ER diagram is [here](https://docs.startsmart.tisuela.com/database/).

Have you programmed any test cases? Let me know where I can find those. 

Also, please make any additions you feel like will help the Frontend team improve the current UI (aka, the `templates` that you've made). This can look like documentation within your `templates`, `views`, `forms`, etc. 

Once you're done with those changes, please make a Pull Request from you branch to `dev` (not `master`). You can also type out documentation **on the pull request** if there's any behavior that other developers should be aware of. Let me know if you need any assistance in that. 

Overall, good work and appreciate the gifs!
